Issue 19 split
sbmlteam/deviser pull request #48
Opened 2021-01-22 11:56 UTC by skeating

## Description

Splits up functions that query elements into separate functions for each element

## Motivation and Context

fixes #19 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated all documentation necessary.
- [ ] I have checked spelling in (new) comments.

2021-01-25 11:27 UTC, mattgillucl requested changes
Thanks Sarah. Looks like a lot of changes were to getbelow the 79 character line limit! Mostly ok, just a couple of minor quibbles.

2021-01-25 11:27 UTC, mattagape commented on generator/parseXML/ParseXML.py
> +In this example: <year>2005</year>, the element node <year> holds a text n
The word "node" has been split!

2021-01-25 11:27 UTC, mattagape commented on generator/parseXML/ParseXML.py
>          parts = tempname.split('_')  # TODO what if tempname is "" or None?
Is this addressed anywhere?

2021-01-25 11:27 UTC, mattagape commented on generator/parseXML/ParseXML.py
> +            # TODO why? and where?
And is this one addressed anywhere?

2021-01-25 11:27 UTC, mattgillucl commented on generator/parseXML/ParseXML.py
> +                # TODO have I explained the above correctly,
Did this get addressed?

2021-01-25 11:27 UTC, mattgillucl commented on generator/parseXML/ParseXML.py
> +        :param element: element to be pdated
typo

2021-01-26 08:59 UTC, skeating commented on generator/parseXML/ParseXML.py
>          parts = tempname.split('_')  # TODO what if tempname is "" or None?
Not sure what you mean by addressed ?

2021-01-26 09:01 UTC, skeating commented on generator/parseXML/ParseXML.py
> +            # TODO why? and where?
no that is why I left the TODO :-)

2021-01-26 09:06 UTC, skeating commented on generator/parseXML/ParseXML.py
> +            # TODO why? and where?
Just to clarify this PR was only addressing the issues I listed; I did not work through any TODOs.  Added an issue to capture this #50

2021-01-26 14:12 UTC, mattgillucl commented on generator/parseXML/ParseXML.py
>          parts = tempname.split('_')  # TODO what if tempname is "" or None?
My mistake. It will never be `None`, as this is checked for immediately above. And is temp is an empty string the `split()` won't complain.

2021-01-26 14:12 UTC, mattgillucl commented on generator/parseXML/ParseXML.py
> +            # TODO why? and where?
Thanks Sarah

2021-01-26 14:13 UTC, mattgillucl approved these changes

2021-01-26 14:14 UTC, mattgillucl commented
@skeating that's great, please go ahead and merge!

2021-01-26 15:39 UTC, merged